/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MAHE
 */
public class ShowDetails extends javax.swing.JFrame {
    private static final String CONN_STRING="jdbc:mysql://localhost:3306/pa?zeroDateTimeBehavior=convertToNull";
    private static final String USER="root";
    private static final String PASS="12345";
    public String x;
    /**
     * Creates new form ShowDetails
     */
    public ShowDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Show Details:");

        jButton1.setText("Back to Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fetch Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("List all of the following:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch", "Subject", "Teacher", "Laboratory", "Department" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton2)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new EntryDetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Connection conn=null;
       Statement stmt=null;
       ResultSet rs=null;
       
       try
       {   Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection(CONN_STRING,USER,PASS);
           stmt=(Statement) conn.createStatement();
           String print_name;
           String check=jComboBox1.getSelectedItem().toString();
           if(check.equals("Branch"))
               print_name="select * from pa_branch";
           else if(check.equals("Subjects"))
               print_name="select * from pa_subjects";
           else if(check.equals("Teacher"))
               print_name="select * from pa_teacher";
           else if(check.equals("Laboratory"))
               print_name="select * from pa_lab";
           
           else 
               print_name="select * from pa_subjects";
           
           
           
               
           
           
           rs=stmt.executeQuery(print_name);
           
           String details;
           if(check.equals("Branch"))
           {   details="Branch Code \t      Branch Name \t      Strength \t       Credits_3 \t     Credits_4 \t      Credits_5 \t     Credits_6 \t      Credits_7 \t     Credits_8 \n________________________________________________________________________________________________________________________________\n";
            while(rs.next())
           {
              String a1=rs.getString("b_code");
              String a2=rs.getString("b_name");
              String a3=rs.getString("strength");
              
              String c3=rs.getString("cre_3");
              String c4=rs.getString("cre_4");
              String c5=rs.getString("cre_5");
              String c6=rs.getString("cre_6");
              String c7=rs.getString("cre_7");
              String c8=rs.getString("cre_8");
              
              details=details+"\n"+a1+"\t"+a2+"\t  \t"+a3+"\t"+c3+"\t"+c4+"\t"+c5+"\t"+c6+"\t"+c7+"\t"+c8+"\n";
              
              jTextArea1.setText(details);
              
               
           }
           
           }
           else if(check.equals("Subject"))
           {   details="Subject Code \t      Subject Name \t      Semester \t       Credits \t     Branch Code \t      Branch Name \t \n___________________________________________________________________________________________\n";
            while(rs.next())
           {
              String a1=rs.getString("s_code");
              String a2=rs.getString("s_name");
              String a3=rs.getString("sem");
              String a4=rs.getString("s_cred");
              String a5=rs.getString("b_code");
              String a6=rs.getString("b_name");
              
              details=details+"\n"+a1+"\t"+a2+"\t  "+a3+"\t"+a4+"\t"+a5+"\t"+a6+"\n";
              
              jTextArea1.setText(details);
              
               
           }
           
           }
           else if(check.equals("Teacher"))
           {   details="Teacher Code \t      Teacher Name \t      Department Name \t\n______________________________________________________________________\n";
            while(rs.next())
           {
              String a1=rs.getString("t_code");
              String a2=rs.getString("t_name");
              String a3=rs.getString("dept_name");
              
              details=details+"\n"+a1+"\t"+a2+"\t  "+a3+"\n";
              
              jTextArea1.setText(details);
              
               
           }
           
           }
           
           else if(check.equals("Laboratory"))
           {   details="Lab Code \t      Lab Name \t      Department Name \t    Credit\n__________________________________________________________________\n";
            while(rs.next())
           {
              String a1=rs.getString("lab_code");
              String a2=rs.getString("lab_name");
              String a3=rs.getString("dept_name");
              String a4=rs.getString("credit");
              
              details=details+"\n"+a1+"\t"+a2+"\t  "+a3+"\t  "+a4+"\n";
              
              jTextArea1.setText(details);
              
               
           }
           
           }
           else if(check.equals("Department"))
           {   details="Department Name \t      HOD Name \t      Founded in\n_______________________________________________________________\n";
            while(rs.next())
           {
              String a1=rs.getString("dept_name");
              String a2=rs.getString("HOD");
              String a3=rs.getString("founded_in");
              
              
              details=details+"\n"+a1+"\t"+a2+"\t  "+a3+"\t  \n";
              
              jTextArea1.setText(details);
              
               
           }
           
           }
           
           
           
           
       }
        catch(Exception e)
                {
                System.out.println("Didn't happen"+e);
                }
           
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
